[project]
name = "suno-adaptive-traffic-light"
version = "0.1.0"
description = "SUNO Adaptive Traffic Light"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.3",
    "questionary>=2.1.1",
    "rich>=15.0.0",
    "stable-baselines3>=2.8.0",
    "sumo-rl>=1.4.5",
    "tqdm>=4.67.3",
    "traci>=1.26.0",
]

[tool.pyright]
extraPaths = ["."]

